# environment.yml

name: stego
channels:
 - pytorch
 - anaconda
 - conda-forge
 - defaults
dependencies:
 - python=3.8.18
 - pip=21.2.4
 - scikit-image
 - opencv
 - cupy
 - pytorch-lightning
 - pip:
     - argcomplete==3.3.0
     - backports-tempfile==1.0
     - backports-weakref==1.0.post1
     - bcrypt==4.1.2
     - cmake==3.29.2
     - contextlib2==21.6.0
     - cycler==0.12.1
     - cython==3.0.10
     - docker==7.0.0
     - humanfriendly==10.0
     - hydra-core==1.3.2
     - importlib-resources==6.4.0
     - isodate==0.6.1
     - jeepney==0.8.0
     - jinja2==3.1.3
     - jmespath==1.0.1
     - jsonpickle==3.0.4
     - kiwisolver==1.4.5
     - knack==0.11.0
     - kornia-rs==0.1.3
     - lit==18.1.3
     - matplotlib==3.3.4
     - mpmath==1.3.0
     - msal==1.28.0
     - msal-extensions==1.1.0
     - msrest==0.7.1
     - msrestazure==0.6.4
     - ndg-httpsclient==0.5.1
     - numpy==1.19.5
     - omegaconf==2.3.0
     - pandas==1.1.5
     - torchvision==0.8.2
     - paramiko==3.4.0
     - pathspec==0.12.1
     - pkginfo==1.10.0
     - portalocker==2.8.2
     - pydensecrf
     - pydeprecate==0.3.1
     - pynacl==1.5.0
     - pyparsing==3.1.2
     - python-dateutil==2.9.0.post0
     - pytz==2024.1
     - scipy==1.5.4
     - seaborn==0.12.2
     - secretstorage==3.3.3
     - setuptools==59.5.0
     - sympy==1.12
     - tabulate==0.9.0
     - tensorboard==2.4.0
     - torch==2.1.0
     - torchpq==0.3.0.6
     - tqdm==4.59.0
     - triton==2.0.0
     - wget